lwcExchangeTrades/force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lwcExchangeTrades/force-app/main/default/objects/Trade__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>ID</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

lwcExchangeTrades/force-app/main/default/classes/TradeTriggerHandler.cls
public with sharing class TradeTriggerHandler {

    private static final String ID_PREFIX = 'TR';
    private static final Integer AMOUNT_OF_ZEROS = 7;
    private static final String STRING_ZERO = '0';
    
    
    public static void fillId (List<Trade__c> trades) {
        List<Trade__c> otherTrades = [
            SELECT Id, ID__c 
            FROM Trade__c 
            ORDER BY ID__c DESC
        ];

        Integer digitalPart = 0;
        if(!otherTrades.isEmpty()) {
            digitalPart = getDigitalPart(otherTrades[0].ID__c);
        } 

        for (Trade__c trade: trades) {
            trade.ID__c = ID_PREFIX + zeroFormatter(++digitalPart);
        }

    }

    private static Integer getDigitalPart (String id) {
        Integer result = 0; 
        if (id != '') {
            result = Integer.valueOf(id.substring(2));
        } 
        return result;
    }

    private static String zeroFormatter (Integer inputNumber) {
        String stringNumber = String.valueOF(inputNumber);
        while(stringNumber.length() < AMOUNT_OF_ZEROS) {
            stringNumber = STRING_ZERO + stringNumber;
        }
        return stringNumber;
    }


}